version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
