# Image Java 21
FROM eclipse-temurin:21-jre

# Work folder in the container
WORKDIR /app

# copied JAR generated by Maven
COPY target/park-house-0.0.1-SNAPSHOT.jar app.jar

# the port exposed by SpringBoot
EXPOSE 8080

# Commande to start the app
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
