create table roles (
    id int generated by default as identity primary key,
    name varchar(32) not null unique
);

create table users (
    id int generated by default as identity primary key,
    username varchar(32) not null unique,
    password_hash text not null
);

create table user_roles (
    user_id int not null references users(id),
    role_id int not null references roles(id),

    primary key (user_id, role_id)
);